version: 2
registries:
  nuget-feed-pkgs-dev-azure-com-443-visiba-packaging-visiba-nuget:
    type: nuget-feed
    url: https://pkgs.dev.azure.com:443/Visiba/_packaging/Visiba/nuget/v3/index.json
    username: "${{secrets.NUGET_FEED_PKGS_DEV_AZURE_COM_443_VISIBA_PACKAGING_VISIBA_NUGET_USERNAME}}"
    password: "${{secrets.NUGET_FEED_PKGS_DEV_AZURE_COM_443_VISIBA_PACKAGING_VISIBA_NUGET_PASSWORD}}"

updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - patrikwlund
  registries:
  - nuget-feed-pkgs-dev-azure-com-443-visiba-packaging-visiba-nuget
